/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const CourseCategory = IDL.Variant({
  'vocals' : IDL.Null,
  'instruments' : IDL.Null,
  'theory' : IDL.Null,
  'dance' : IDL.Null,
});
export const Course = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'description' : IDL.Text,
  'lessonIds' : IDL.Vec(IDL.Text),
  'createdTimestamp' : IDL.Int,
  'category' : CourseCategory,
  'priceCents' : IDL.Nat,
  'instructorName' : IDL.Text,
});
export const Lesson = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'contentUrl' : IDL.Text,
  'description' : IDL.Text,
  'durationMinutes' : IDL.Nat,
  'courseId' : IDL.Text,
  'orderIndex' : IDL.Nat,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
});
export const Enrollment = IDL.Record({
  'paymentStatus' : PaymentStatus,
  'userId' : IDL.Principal,
  'enrolledAt' : IDL.Int,
  'stripePaymentIntentId' : IDL.Text,
  'courseId' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
});
export const Progress = IDL.Record({
  'lastAccessed' : IDL.Int,
  'userId' : IDL.Principal,
  'completedLessonIds' : IDL.Vec(IDL.Text),
  'courseId' : IDL.Text,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkCoursePaymentStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createCoursePaymentSession' : IDL.Func([IDL.Text], [IDL.Text], []),
  'createOrUpdateCourse' : IDL.Func([Course], [], []),
  'createOrUpdateLesson' : IDL.Func([Lesson], [], []),
  'deleteCourse' : IDL.Func([IDL.Text], [], []),
  'enrollUserInCourse' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getAllEnrollments' : IDL.Func([], [IDL.Vec(Enrollment)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCourse' : IDL.Func([IDL.Text], [IDL.Opt(Course)], ['query']),
  'getCourseProgressForUser' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [IDL.Opt(Progress)],
      ['query'],
    ),
  'getCourseRecommendations' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getEnrollmentsForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Enrollment)],
      ['query'],
    ),
  'getLesson' : IDL.Func([IDL.Text], [IDL.Opt(Lesson)], ['query']),
  'getLessonsForCourse' : IDL.Func([IDL.Text], [IDL.Vec(Lesson)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateLessonProgress' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const CourseCategory = IDL.Variant({
    'vocals' : IDL.Null,
    'instruments' : IDL.Null,
    'theory' : IDL.Null,
    'dance' : IDL.Null,
  });
  const Course = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'description' : IDL.Text,
    'lessonIds' : IDL.Vec(IDL.Text),
    'createdTimestamp' : IDL.Int,
    'category' : CourseCategory,
    'priceCents' : IDL.Nat,
    'instructorName' : IDL.Text,
  });
  const Lesson = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'contentUrl' : IDL.Text,
    'description' : IDL.Text,
    'durationMinutes' : IDL.Nat,
    'courseId' : IDL.Text,
    'orderIndex' : IDL.Nat,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Enrollment = IDL.Record({
    'paymentStatus' : PaymentStatus,
    'userId' : IDL.Principal,
    'enrolledAt' : IDL.Int,
    'stripePaymentIntentId' : IDL.Text,
    'courseId' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
  });
  const Progress = IDL.Record({
    'lastAccessed' : IDL.Int,
    'userId' : IDL.Principal,
    'completedLessonIds' : IDL.Vec(IDL.Text),
    'courseId' : IDL.Text,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkCoursePaymentStatus' : IDL.Func(
        [IDL.Text],
        [StripeSessionStatus],
        [],
      ),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createCoursePaymentSession' : IDL.Func([IDL.Text], [IDL.Text], []),
    'createOrUpdateCourse' : IDL.Func([Course], [], []),
    'createOrUpdateLesson' : IDL.Func([Lesson], [], []),
    'deleteCourse' : IDL.Func([IDL.Text], [], []),
    'enrollUserInCourse' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getAllEnrollments' : IDL.Func([], [IDL.Vec(Enrollment)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCourse' : IDL.Func([IDL.Text], [IDL.Opt(Course)], ['query']),
    'getCourseProgressForUser' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [IDL.Opt(Progress)],
        ['query'],
      ),
    'getCourseRecommendations' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getEnrollmentsForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Enrollment)],
        ['query'],
      ),
    'getLesson' : IDL.Func([IDL.Text], [IDL.Opt(Lesson)], ['query']),
    'getLessonsForCourse' : IDL.Func([IDL.Text], [IDL.Vec(Lesson)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateLessonProgress' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };