/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Course {
  'id' : string,
  'title' : string,
  'thumbnailUrl' : string,
  'description' : string,
  'lessonIds' : Array<string>,
  'createdTimestamp' : bigint,
  'category' : CourseCategory,
  'priceCents' : bigint,
  'instructorName' : string,
}
export type CourseCategory = { 'vocals' : null } |
  { 'instruments' : null } |
  { 'theory' : null } |
  { 'dance' : null };
export interface Enrollment {
  'paymentStatus' : PaymentStatus,
  'userId' : Principal,
  'enrolledAt' : bigint,
  'stripePaymentIntentId' : string,
  'courseId' : string,
}
export interface Lesson {
  'id' : string,
  'title' : string,
  'contentUrl' : string,
  'description' : string,
  'durationMinutes' : bigint,
  'courseId' : string,
  'orderIndex' : bigint,
}
export type PaymentStatus = { 'pending' : null } |
  { 'completed' : null };
export interface Progress {
  'lastAccessed' : bigint,
  'userId' : Principal,
  'completedLessonIds' : Array<string>,
  'courseId' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'bio' : string,
  'name' : string,
  'role' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkCoursePaymentStatus' : ActorMethod<[string], StripeSessionStatus>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createCoursePaymentSession' : ActorMethod<[string], string>,
  'createOrUpdateCourse' : ActorMethod<[Course], undefined>,
  'createOrUpdateLesson' : ActorMethod<[Lesson], undefined>,
  'deleteCourse' : ActorMethod<[string], undefined>,
  'enrollUserInCourse' : ActorMethod<[string, string], undefined>,
  'getAllCourses' : ActorMethod<[], Array<Course>>,
  'getAllEnrollments' : ActorMethod<[], Array<Enrollment>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCourse' : ActorMethod<[string], [] | [Course]>,
  'getCourseProgressForUser' : ActorMethod<
    [Principal, string],
    [] | [Progress]
  >,
  'getCourseRecommendations' : ActorMethod<[], Array<Course>>,
  'getEnrollmentsForUser' : ActorMethod<[Principal], Array<Enrollment>>,
  'getLesson' : ActorMethod<[string], [] | [Lesson]>,
  'getLessonsForCourse' : ActorMethod<[string], Array<Lesson>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateLessonProgress' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];